### ISSUE TITLE
Add Body Battery 

### ISSUE THREAD

**Issue by chicodefe** [warmsound/crystal-face#176] opened 2020-10-19 07:19 UTC
Add Body Battery

**Comment by flocsy** [comment] 2021-07-04 09:28
IMHO this is a duplicate of https://github.com/warmsound/crystal-face/issues/135

**Comment by warmsound** [comment] 2024-01-01 09:20
Closing as duplicate. Feature will be implemented shortly.

**Closed by warmsound** 2024-01-01 09:20 UTC
