### ISSUE TITLE
Calorie meter causes crash on Vivoactive 3 Music

### ISSUE THREAD

**Issue by medley56** [warmsound/crystal-face#129] opened 2019-06-02 14:05 UTC
This (nearly) consistently crashes the watch face on my Vivoactive 3 Music. To reproduce, set Left Meter or Right Meter to "Calories (Manual Goal)". When settings are saved the watch face crashes and the watch defaults back to the Garmin face. When Left/Right Meter setting is changed to anything other than Calories, the face starts working and can be set on the watch again.

Caveat. I managed to get it to work 1 single time. No idea what was different. Tried it again and it crashed as usual.

**Comment by warmsound** [comment] 2019-06-19 22:15
@medley56, thanks for your detailed description of this issue. This is almost certainly the same issue as #123 (I presume you're using the Connect IQ Store mobile app). I've only just found the cause of the issue, so hopefully I'll have a fix out in the next few days. I'll close this one, and use #123 to track the issue.

**Closed by warmsound** 2019-06-19 22:15 UTC
